title:             Bearjin
email:             wj.kim@theuber.co.kr
description:       Bearjin Blog
author:            wj.kim
baseurl:           ""
url:               "https://bearjin.github.io/"

# Social Profiles
github_username:   bearjin

# Build settings
markdown:          kramdown
paginate:          5
paginate_path:     "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
